:%s/\`\`/\"/g
:%s:\\texttt{\"\([^}]*\)\"}:<b>\1</b>:g
:%s:\\textbf{\"\([^}]*\)\"}:<b>\1</b>:g
:%s:\\texttt{\([^}]*\)}:<code>\1</code>:g
:%s/\\ref{[^}]*}//g
:%s/\\marginlabel{[^}]*}//g
:%s/\\index{[^}]*}//g
:%s/\\seealso{[^}]*}//g
:%s/\\begin{[^}]*}//g
:%s/\\end{[^}]*}//g
:wq
